const questionsRACV = [
    {q: "¿Com s'escriu la conjunció copulativa en les Normes d'El Puig?", o: ["y", "i", "hi"], a: 0},
    {q: "¿Quin pronom de primera persona s'usa oficialment?", o: ["Jo", "Ieu", "Yo"], a: 2},
    {q: "¿Com s'escriu la paraula per referir-se a un chiquet?", o: ["Xiquet", "Txiquet", "Chiquet"], a: 2},
    {q: "¿Quina lletra NO existix en l'abecedari valencià de la RACV?", o: ["La 'y' grega", "La 'ç' (ce trencada)", "La 'h' intercalada"], a: 1},
    {q: "¿Cóm s'accentua el nom de la nostra capital?", o: ["Valéncia", "València", "Valencia"], a: 0},
    {q: "¿Quin és el demostratiu correcte de proximitat masculí?", o: ["Aquest", "Este", "Aqueste"], a: 1},
    {q: "¿Cóm fan el plural les paraules acabaes en -a àtona?", o: ["En -es (chiquetes)", "En -as (chiquetas)", "Sense canvi"], a: 0},
    {q: "¿Quin accent gràfic s'utilisa en les Normes per a marcar les vocals tòniques?", o: ["Obert (`)", "Tancat o agut (´)", "Cercumflex (^)"], a: 1},
    {q: "En general, els verbs acabats en -isar s'escriuen en...", o: ["-izar (organizar)", "-isar (organisar)", "-itzar (organitzar)"], a: 1},
    {q: "La terminació de l'imperfet d'indicatiu de la 1ª conjugació s'escriu en:", o: ["-aba (cantaba)", "-ava (cantava)", "-avva"], a: 1},
    {q: "¿Quin és el topònim genuí valencià (defés per la RACV) per a la ciutat de les palmeres?", o: ["Elx", "Elig", "Elche"], a: 1},
    {q: "Al no usar-se la 'ce trencada' en les Normes, ¿cóm s'escriu este poble de l'Horta Nort?", o: ["Puçol", "Pusol", "Pussol"], a: 1},
    {q: "¿Cóm s'escriu correctament la província més al nort del Regne?", o: ["Castelló", "Castellò", "Castellon"], a: 0},
    {q: "¿Cóm s'escriu el topònim del poble famós pel seu castell a La Costera?", o: ["Montesa", "Montessa", "Muntesa"], a: 0},
    {q: "¿Quína d'estes paraules s'escriu sense la lletra 'h' en valencià autèntic?", o: ["Hivern", "Hui", "Ome (Home)"], a: 2}, 
    {q: "La paraula referida a la festa del foc s'escriu:", o: ["Falles", "Fallas", "Fales"], a: 0},
    {q: "¿Cóm s'escriu l'acció de posar-se dret?", o: ["Alçar-se", "Alsar-se", "Alzar-se"], a: 1},
    {q: "¿Quin article definit femení s'utilisa de forma general (i normativa)?", o: ["La / Les", "Sa / Ses", "Na / Nes"], a: 0},
    {q: "¿Cóm s'escriu la via per a on circulen els cotxes?", o: ["Carrer", "Carré", "Karrer"], a: 0},
    {q: "El gentilici de Valéncia en masculí plural és:", o: ["Valencians", "Valencianos", "Valencianes"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'servei'?", o: ["servici", "servei", "sirvici"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'mitjans'?", o: ["mijos", "mitjans", "medis"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'altres'?", o: ["atres", "altres", "otres"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'nosaltres'?", o: ["mosatros", "nosaltres", "mosotros"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'veure'?", o: ["vore", "veure", "ver"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'tarda'?", o: ["vesprada", "tarda", "tarde"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'aviat'?", o: ["prompte", "aviat", "pronto"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'vermell'?", o: ["roig", "vermell", "royo"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'vuit'?", o: ["huit", "vuit", "ocho"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'dinou'?", o: ["dènou", "dinou", "decenou"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'mirall'?", o: ["espill", "mirall", "espejo"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'llonganissa'?", o: ["llongonissa", "llonganissa", "longanisa"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'força'?", o: ["forsa", "força", "fuerza"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'xufa'?", o: ["chufa", "xufa", "txufa"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'xarrar'?", o: ["charrar", "xarrar", "parlar"], a: 0},
    {q: "¿Quína és la forma més genuïna en la RACV per a dir 'desenvolupament'?", o: ["desenroll", "desenvolupament", "desarroll"], a: 0},
    {q: "¿Cóm es forma el plural de 'chiquet'?", o: ["chiquetes", "chiquets", "chiquetus"], a: 1},
    {q: "¿Quina és l'ortografia correcta per al número 16?", o: ["Seze", "Setze", "Dèsis"], a: 0},
    {q: "¿Cóm s'escriu l'acció de buscar?", o: ["Buscar", "Cercar", "Busquar"], a: 0},
    {q: "¿Cóm s'escriu l'article neutre en les Normes d'El Puig?", o: ["Lo", "El", "Ho"], a: 0},
    {q: "El plural de 'mà' (mano) és:", o: ["Mans", "Manes", "Màns"], a: 0},
    {q: "En valencià, el menjar del migdia s'anomena:", o: ["Dinar", "Esmorzar", "Sopar"], a: 0},
    {q: "El contrari de 'nit' és:", o: ["Dia", "Jorn", "Matí"], a: 0},
    {q: "¿Cóm s'escriu el color del cel clar?", o: ["Blau", "Azul", "Celest"], a: 0},
    {q: "¿Quin verb s'usa per a dir 'salir'?", o: ["Eixir", "Sortir", "Sallir"], a: 0},
    {q: "¿Com s'escriu l'animal que lladra?", o: ["Gos", "Ca", "Perro"], a: 0},
    {q: "¿Cóm s'escriu el nombre 20?", o: ["Vint", "Vuit", "Vinti"], a: 0},
    {q: "¿Cóm s'escriu la capital d'Espanya en valencià normatiu?", o: ["Madrít", "Madrid", "Madrit"], a: 2},
    {q: "¿Cóm es diu 'hoy' en valencià autèntic?", o: ["Hui", "Avui", "Oí"], a: 0},
    {q: "¿Cóm s'escriu el lloc on comprem el pa?", o: ["Forn", "Panaderia", "Fleca"], a: 0},
    {q: "¿Com es diu el germà de ton pare?", o: ["Tio", "Oncle", "Tiet"], a: 0},
    {q: "L'expressió per a donar les gràcies és:", o: ["Gràcies", "Mercé", "Merçi"], a: 0},
    {q: "L'arbre que dona taronges és un...", o: ["Taronger", "Taronjo", "Tarongera"], a: 0},
    {q: "¿Cóm s'escriu l'habitació on es cuina?", o: ["Cuina", "Cocina", "Coina"], a: 0},
    {q: "¿Cóm es diu 'ventana' en valencià?", o: ["Finestra", "Ventana", "Vidal"], a: 0},
    {q: "¿Cóm s'escriu la persona que governa un ajuntament?", o: ["Alcalde", "Batle", "Alcaldi"], a: 0},
    {q: "¿Cóm es diu 'mucho' en valencià normatiu?", o: ["Molt", "Gaire", "Munch"], a: 0},
    {q: "¿Cóm s'escriu l'au símbol de l'Albufera?", o: ["Ànec", "Pato", "Anec"], a: 0},
    {q: "¿Quin d'estos pobles està en la Plana Baixa?", o: ["Vila-real", "Villarreal", "Vilareal"], a: 0},
    {q: "¿Cóm s'escriu el riu de Cullera?", o: ["Xúquer", "Chúquer", "Xuquer"], a: 0},
    {q: "El topònim correcte de la ciutat turística és:", o: ["Benidorm", "Benidorme", "Binidorm"], a: 0},
    {q: "La comarca d'Alzira és...", o: ["La Ribera Alta", "La Ribera Baixa", "L'Horta"], a: 0},
    {q: "¿Com s'escriu l'acció d'obrir els ulls en nàixer?", o: ["Naixer", "Néixer", "Naixre"], a: 0},
    {q: "¿Quina d'estes formes de relatiu és normativa en RACV?", o: ["Lo qual", "El qual", "Lo que"], a: 0},
    {q: "¿Com s'escriu la paraula per a un poal d'aigua?", o: ["Poal", "Galleda", "Cubo"], a: 0},
    {q: "¿Com s'escriu el color de la neu?", o: ["Blanc", "Albo", "Blanco"], a: 0},
    {q: "¿Com es diu 'Naranja' en valencià?", o: ["Taronja", "Naronja", "Tarongia"], a: 0},
    {q: "¿Com es diu 'Silla' en valencià?", o: ["Cadira", "Silla", "Cadeira"], a: 0},
    {q: "¿Com es diu 'Mesa' en valencià?", o: ["Taula", "Mesa", "Mensa"], a: 0},
    {q: "¿Com es diu 'Cuchara' en valencià?", o: ["Cullera", "Cuchara", "Culler"], a: 0},
    {q: "¿Com es diu 'Tenedor' en valencià?", o: ["Forqueta", "Tenedor", "Tenedò"], a: 0},
    {q: "¿Com es diu 'Cuchillo' en valencià?", o: ["Ganet", "Cuchillo", "Coltell"], a: 0},
    {q: "¿Com es diu 'Vaso' en valencià?", o: ["Got", "Vaso", "Gote"], a: 0},
    {q: "¿Com es diu 'Plato' en valencià?", o: ["Plat", "Plato", "Plet"], a: 0},
    {q: "¿Com es diu 'Servilleta' en valencià?", o: ["Torcaboques / Servilleta", "Tovalló", "Mocador"], a: 0},
    {q: "¿Com es diu 'Pantalón' en valencià?", o: ["Pantaló", "Pantalons", "Pantalo"], a: 0},
    {q: "¿Com es diu 'Camisa' en valencià?", o: ["Camisa", "Camesa", "Camicia"], a: 0},
    {q: "¿Com es diu 'Zapatos' en valencià?", o: ["Sabates", "Zapatos", "Sabatos"], a: 0},
    {q: "¿Com es diu 'Calcetines' en valencià?", o: ["Mijetes", "Calcetins", "Calces"], a: 0},
    {q: "¿Com es diu 'Sombrero' en valencià?", o: ["Capell", "Sombrero", "Barret"], a: 0},
    {q: "¿Com es diu 'Reloj' en valencià?", o: ["Rellonge", "Reloj", "Rellotge"], a: 0},
    {q: "¿Com es diu 'Gafas' en valencià?", o: ["Ulleres", "Gafas", "Lents"], a: 0},
    {q: "¿Com es diu 'Lápiz' en valencià?", o: ["Llapiser", "Llapiz", "Llapís"], a: 0},
    {q: "¿Com es diu 'Bolígrafo' en valencià?", o: ["Bolígraf", "Ploma", "Boli"], a: 0},
    {q: "¿Com es diu 'Papel' en valencià?", o: ["Paper", "Papel", "Foli"], a: 0},
    {q: "¿Com es diu 'Libro' en valencià?", o: ["Llibre", "Libro", "Lliebre"], a: 0},
    {q: "¿Com es diu 'Coche' en valencià?", o: ["Coche", "Cotxe", "Carro"], a: 0},
    {q: "¿Com es diu 'Bicicleta' en valencià?", o: ["Bicicleta", "Bici", "Biciclete"], a: 0},
    {q: "¿Com es diu 'Tren' en valencià?", o: ["Tren", "Treno", "Tran"], a: 0},
    {q: "¿Com es diu 'Avión' en valencià?", o: ["Avió", "Avion", "Aeroplà"], a: 0},
    {q: "¿Com es diu 'Gato' en valencià?", o: ["Gat", "Gato", "Mixo"], a: 0},
    {q: "¿Com es diu 'Caballo' en valencià?", o: ["Cavall", "Caball", "Cabal"], a: 0},
    {q: "¿Com es diu 'Vaca' en valencià?", o: ["Vaca", "Vaqueta", "Baca"], a: 0},
    {q: "¿Com es diu 'Cerdo' en valencià?", o: ["Porc", "Cerdo", "Gorrino"], a: 0},
    {q: "¿Com es diu 'Oveja' en valencià?", o: ["Ovella", "Oveja", "Olla"], a: 0},
    {q: "¿Cóm s'escriu el riu de Valéncia?", o: ["Túria", "Turia", "Xúquer"], a: 0},
    {q: "¿Cóm s'escriu l'acció de posar ordre?", o: ["Organisar", "Organizar", "Organitzar"], a: 0},
    {q: "¿Quin poble està en la comarca dels Serrans?", o: ["Xelva", "Chelva", "Selva"], a: 1},
    {q: "¿Com s'escriu la flor de l'arròs i de la taronja?", o: ["Flor del taronger", "Azahar", "Flor de l'azahar"], a: 0},
    {q: "¿Cóm es diu 'ventana' en valencià?", o: ["Finestra", "Vidal", "Ventana"], a: 0}
];
