services:
  web:
    image: caddy:alpine
    container_name: radiovalencianismo-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  icecast:
    image: pltnk/icecast2
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./backend/icecast.xml:/etc/icecast.xml:ro
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:main
    container_name: liquidsoap
    ports:
      - "8080:8080"
      - "1234:1234"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./backend/radio.liq:/etc/liquidsoap/radio.liq:ro
      - ./backend/mp3:/mp3:ro
    command: ["liquidsoap", "/etc/liquidsoap/radio.liq"]
    depends_on:
      - icecast
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.valencianismo.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.valencianismo.com/
      - TZ=Europe/Madrid
      # Mantengo estos por si decides activarlos en el panel más adelante
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=v0l0v 
      - N8N_BASIC_AUTH_PASSWORD=D26VmLg3791+
      - N8N_BLOCK_EXECV=false
      - N8N_COMMAND_TIMEOUT=30000
      - NODES_EXCLUDE=[]
      # Quitado N8N_NODES_INCLUDE para permitir que carguen todos los nodos
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/node/radiovalencianismo:rw

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  caddy_data:
  caddy_config:
  n8n_data:
  portainer_data:
