services:
  web:
    image: caddy:alpine
    container_name: radiovalencianismo-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  icecast:
    image: pltnk/icecast2
    container_name: icecast
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend/icecast.xml:/etc/icecast.xml:ro
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:main
    container_name: liquidsoap
    ports:
      - "8080:8080"
      - "127.0.0.1:1234:1234"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./backend/radio.liq:/etc/liquidsoap/radio.liq:ro
      - ./backend/mp3:/mp3:rw
    command: [ "liquidsoap", "/etc/liquidsoap/radio.liq" ]
    depends_on:
      - icecast
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  piper-tts:
    image: artibex/piper-http:latest
    container_name: piper-tts
    ports:
      - "127.0.0.1:5500:5000"
    environment:
      - MODEL_DOWNLOAD_LINK=https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx?download=true
    volumes:
      - piper_data:/app/models
    restart: unless-stopped


volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  portainer_data:
    driver: local
  piper_data:
    driver: local
